on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
env:
  TIMESTAMP: ${{ date "+%Y-%m-%d-%H:%M" }}
      
jobs:    
 build:
      runs-on: windows-latest

      steps:
        - name: Test1
          run: echo ${{ env.TIMESTAMP}}
