on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:    
 build:
      runs-on: windows-latest

      steps:
        - name: Set current date as env variable
          run: echo "NOW::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
        - name: Echo current date
          run: echo $NOW
