name: CI
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${{ github.ref_name }}
